#!/bin/sh

if [[ -z "$ETCD_PORT_4001_TCP_ADDR" ]]
then
    . /app/conf/varnish_vars
    handlebars --redirects "$VARNISH_REDIRECTS" --apps "$VARNISH_APPS" < /app/conf/varnish.vcl.handlebars
else
    ETCD_HOST=$ETCD_PORT_4001_TCP_ADDR:$ETCD_PORT_4001_TCP_PORT
    handlebars --redirects "`etcd-varnish get redirects`" --apps "`etcd-varnish get apps`" < /app/conf/varnish.vcl.handlebars
fi
