#!/bin/sh

# generate conf
/app/generate-conf > /tmp/default.vcl

# reload if different
( cmp -s /tmp/default.vcl /etc/varnish/default.vcl \
 || ( \
    cp /tmp/default.vcl /etc/varnish/default.vcl ; \
    NAME=`date +reload_%s%N` ; \
       (
         varnishadm vcl.load $NAME /etc/varnish/default.vcl \
         && varnishadm vcl.use $NAME \
       ) \
    ) \
) 2>&1 >> /log/varnish-reload.log
